FROM valory/open-aea-user:0.1.0

RUN cowsay "This is a developement image!"
COPY watcher.py dev_requirements.txt ./
ENTRYPOINT ["/bin/python"]
RUN pip install -r dev_requirements.txt
CMD ["watcher.py"]
