# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/types/params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2

from packages.valory.connections.abci.gogoproto import (
    gogo_pb2 as gogoproto_dot_gogo__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dtendermint/types/params.proto\x12\x10tendermint.types\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/duration.proto"\xdb\x01\n\x0f\x43onsensusParams\x12,\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x1d.tendermint.types.BlockParams\x12\x32\n\x08\x65vidence\x18\x02 \x01(\x0b\x32 .tendermint.types.EvidenceParams\x12\x34\n\tvalidator\x18\x03 \x01(\x0b\x32!.tendermint.types.ValidatorParams\x12\x30\n\x07version\x18\x04 \x01(\x0b\x32\x1f.tendermint.types.VersionParams"1\n\x0b\x42lockParams\x12\x11\n\tmax_bytes\x18\x01 \x01(\x03\x12\x0f\n\x07max_gas\x18\x02 \x01(\x03"~\n\x0e\x45videnceParams\x12\x1a\n\x12max_age_num_blocks\x18\x01 \x01(\x03\x12=\n\x10max_age_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\x12\x11\n\tmax_bytes\x18\x03 \x01(\x03"(\n\x0fValidatorParams\x12\x15\n\rpub_key_types\x18\x01 \x03(\t"$\n\rVersionParams\x12\x13\n\x0b\x61pp_version\x18\x01 \x01(\x04">\n\x0cHashedParams\x12\x17\n\x0f\x62lock_max_bytes\x18\x01 \x01(\x03\x12\x15\n\rblock_max_gas\x18\x02 \x01(\x03\x42=Z7github.com/tendermint/tendermint/proto/tendermint/types\xa8\xe2\x1e\x01\x62\x06proto3'
)


_CONSENSUSPARAMS = DESCRIPTOR.message_types_by_name["ConsensusParams"]
_BLOCKPARAMS = DESCRIPTOR.message_types_by_name["BlockParams"]
_EVIDENCEPARAMS = DESCRIPTOR.message_types_by_name["EvidenceParams"]
_VALIDATORPARAMS = DESCRIPTOR.message_types_by_name["ValidatorParams"]
_VERSIONPARAMS = DESCRIPTOR.message_types_by_name["VersionParams"]
_HASHEDPARAMS = DESCRIPTOR.message_types_by_name["HashedParams"]
ConsensusParams = _reflection.GeneratedProtocolMessageType(
    "ConsensusParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONSENSUSPARAMS,
        "__module__": "tendermint.types.params_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.types.ConsensusParams)
    },
)
_sym_db.RegisterMessage(ConsensusParams)

BlockParams = _reflection.GeneratedProtocolMessageType(
    "BlockParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _BLOCKPARAMS,
        "__module__": "tendermint.types.params_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.types.BlockParams)
    },
)
_sym_db.RegisterMessage(BlockParams)

EvidenceParams = _reflection.GeneratedProtocolMessageType(
    "EvidenceParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVIDENCEPARAMS,
        "__module__": "tendermint.types.params_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.types.EvidenceParams)
    },
)
_sym_db.RegisterMessage(EvidenceParams)

ValidatorParams = _reflection.GeneratedProtocolMessageType(
    "ValidatorParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _VALIDATORPARAMS,
        "__module__": "tendermint.types.params_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.types.ValidatorParams)
    },
)
_sym_db.RegisterMessage(ValidatorParams)

VersionParams = _reflection.GeneratedProtocolMessageType(
    "VersionParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _VERSIONPARAMS,
        "__module__": "tendermint.types.params_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.types.VersionParams)
    },
)
_sym_db.RegisterMessage(VersionParams)

HashedParams = _reflection.GeneratedProtocolMessageType(
    "HashedParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _HASHEDPARAMS,
        "__module__": "tendermint.types.params_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.types.HashedParams)
    },
)
_sym_db.RegisterMessage(HashedParams)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z7github.com/tendermint/tendermint/proto/tendermint/types\250\342\036\001"
    )
    _EVIDENCEPARAMS.fields_by_name["max_age_duration"]._options = None
    _EVIDENCEPARAMS.fields_by_name[
        "max_age_duration"
    ]._serialized_options = b"\310\336\037\000\230\337\037\001"
    _CONSENSUSPARAMS._serialized_start = 106
    _CONSENSUSPARAMS._serialized_end = 325
    _BLOCKPARAMS._serialized_start = 327
    _BLOCKPARAMS._serialized_end = 376
    _EVIDENCEPARAMS._serialized_start = 378
    _EVIDENCEPARAMS._serialized_end = 504
    _VALIDATORPARAMS._serialized_start = 506
    _VALIDATORPARAMS._serialized_end = 546
    _VERSIONPARAMS._serialized_start = 548
    _VERSIONPARAMS._serialized_end = 584
    _HASHEDPARAMS._serialized_start = 586
    _HASHEDPARAMS._serialized_end = 648
# @@protoc_insertion_point(module_scope)
