# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tendermint/version/types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from packages.valory.connections.abci.gogoproto import (
    gogo_pb2 as gogoproto_dot_gogo__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1etendermint/version/types.proto\x12\x12tendermint.version\x1a\x14gogoproto/gogo.proto"-\n\tConsensus\x12\r\n\x05\x62lock\x18\x01 \x01(\x04\x12\x0b\n\x03\x61pp\x18\x02 \x01(\x04:\x04\xe8\xa0\x1f\x01\x42;Z9github.com/tendermint/tendermint/proto/tendermint/versionb\x06proto3'
)


_CONSENSUS = DESCRIPTOR.message_types_by_name["Consensus"]
Consensus = _reflection.GeneratedProtocolMessageType(
    "Consensus",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONSENSUS,
        "__module__": "tendermint.version.types_pb2"
        # @@protoc_insertion_point(class_scope:tendermint.version.Consensus)
    },
)
_sym_db.RegisterMessage(Consensus)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z9github.com/tendermint/tendermint/proto/tendermint/version"
    )
    _CONSENSUS._options = None
    _CONSENSUS._serialized_options = b"\350\240\037\001"
    _CONSENSUS._serialized_start = 76
    _CONSENSUS._serialized_end = 121
# @@protoc_insertion_point(module_scope)
