# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipfs.proto

import sys


_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="ipfs.proto",
    package="aea.valory.ipfs.v0_1_0",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\nipfs.proto\x12\x16\x61\x65\x61.valory.ipfs.v0_1_0"\xb2\x07\n\x0bIpfsMessage\x12G\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x36.aea.valory.ipfs.v0_1_0.IpfsMessage.Error_PerformativeH\x00\x12G\n\x05\x66iles\x18\x06 \x01(\x0b\x32\x36.aea.valory.ipfs.v0_1_0.IpfsMessage.Files_PerformativeH\x00\x12O\n\tget_files\x18\x07 \x01(\x0b\x32:.aea.valory.ipfs.v0_1_0.IpfsMessage.Get_Files_PerformativeH\x00\x12O\n\tipfs_hash\x18\x08 \x01(\x0b\x32:.aea.valory.ipfs.v0_1_0.IpfsMessage.Ipfs_Hash_PerformativeH\x00\x12S\n\x0bstore_files\x18\t \x01(\x0b\x32<.aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_PerformativeH\x00\x1a\xc9\x01\n\x18Store_Files_Performative\x12V\n\x05\x66iles\x18\x01 \x03(\x0b\x32G.aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.FilesEntry\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\x12\x16\n\x0etimeout_is_set\x18\x03 \x01(\x08\x1a,\n\nFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\x16Ipfs_Hash_Performative\x12\x11\n\tipfs_hash\x18\x01 \x01(\t\x1aT\n\x16Get_Files_Performative\x12\x11\n\tipfs_hash\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\x12\x16\n\x0etimeout_is_set\x18\x03 \x01(\x08\x1a\x94\x01\n\x12\x46iles_Performative\x12P\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x41.aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative.FilesEntry\x1a,\n\nFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a$\n\x12\x45rror_Performative\x12\x0e\n\x06reason\x18\x01 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
    ),
)


_IPFSMESSAGE_STORE_FILES_PERFORMATIVE_FILESENTRY = _descriptor.Descriptor(
    name="FilesEntry",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.FilesEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.FilesEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.FilesEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=_b("8\001"),
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=605,
    serialized_end=649,
)

_IPFSMESSAGE_STORE_FILES_PERFORMATIVE = _descriptor.Descriptor(
    name="Store_Files_Performative",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="files",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.files",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="timeout",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.timeout",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="timeout_is_set",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.timeout_is_set",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _IPFSMESSAGE_STORE_FILES_PERFORMATIVE_FILESENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=448,
    serialized_end=649,
)

_IPFSMESSAGE_IPFS_HASH_PERFORMATIVE = _descriptor.Descriptor(
    name="Ipfs_Hash_Performative",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Ipfs_Hash_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ipfs_hash",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Ipfs_Hash_Performative.ipfs_hash",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=651,
    serialized_end=694,
)

_IPFSMESSAGE_GET_FILES_PERFORMATIVE = _descriptor.Descriptor(
    name="Get_Files_Performative",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Get_Files_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ipfs_hash",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Get_Files_Performative.ipfs_hash",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="timeout",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Get_Files_Performative.timeout",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="timeout_is_set",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Get_Files_Performative.timeout_is_set",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=696,
    serialized_end=780,
)

_IPFSMESSAGE_FILES_PERFORMATIVE_FILESENTRY = _descriptor.Descriptor(
    name="FilesEntry",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative.FilesEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative.FilesEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative.FilesEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=_b("8\001"),
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=605,
    serialized_end=649,
)

_IPFSMESSAGE_FILES_PERFORMATIVE = _descriptor.Descriptor(
    name="Files_Performative",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="files",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative.files",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _IPFSMESSAGE_FILES_PERFORMATIVE_FILESENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=783,
    serialized_end=931,
)

_IPFSMESSAGE_ERROR_PERFORMATIVE = _descriptor.Descriptor(
    name="Error_Performative",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Error_Performative",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="reason",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.Error_Performative.reason",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=933,
    serialized_end=969,
)

_IPFSMESSAGE = _descriptor.Descriptor(
    name="IpfsMessage",
    full_name="aea.valory.ipfs.v0_1_0.IpfsMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="error",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.error",
            index=0,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="files",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.files",
            index=1,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="get_files",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.get_files",
            index=2,
            number=7,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ipfs_hash",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.ipfs_hash",
            index=3,
            number=8,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="store_files",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.store_files",
            index=4,
            number=9,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _IPFSMESSAGE_STORE_FILES_PERFORMATIVE,
        _IPFSMESSAGE_IPFS_HASH_PERFORMATIVE,
        _IPFSMESSAGE_GET_FILES_PERFORMATIVE,
        _IPFSMESSAGE_FILES_PERFORMATIVE,
        _IPFSMESSAGE_ERROR_PERFORMATIVE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="performative",
            full_name="aea.valory.ipfs.v0_1_0.IpfsMessage.performative",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=39,
    serialized_end=985,
)

_IPFSMESSAGE_STORE_FILES_PERFORMATIVE_FILESENTRY.containing_type = (
    _IPFSMESSAGE_STORE_FILES_PERFORMATIVE
)
_IPFSMESSAGE_STORE_FILES_PERFORMATIVE.fields_by_name[
    "files"
].message_type = _IPFSMESSAGE_STORE_FILES_PERFORMATIVE_FILESENTRY
_IPFSMESSAGE_STORE_FILES_PERFORMATIVE.containing_type = _IPFSMESSAGE
_IPFSMESSAGE_IPFS_HASH_PERFORMATIVE.containing_type = _IPFSMESSAGE
_IPFSMESSAGE_GET_FILES_PERFORMATIVE.containing_type = _IPFSMESSAGE
_IPFSMESSAGE_FILES_PERFORMATIVE_FILESENTRY.containing_type = (
    _IPFSMESSAGE_FILES_PERFORMATIVE
)
_IPFSMESSAGE_FILES_PERFORMATIVE.fields_by_name[
    "files"
].message_type = _IPFSMESSAGE_FILES_PERFORMATIVE_FILESENTRY
_IPFSMESSAGE_FILES_PERFORMATIVE.containing_type = _IPFSMESSAGE
_IPFSMESSAGE_ERROR_PERFORMATIVE.containing_type = _IPFSMESSAGE
_IPFSMESSAGE.fields_by_name["error"].message_type = _IPFSMESSAGE_ERROR_PERFORMATIVE
_IPFSMESSAGE.fields_by_name["files"].message_type = _IPFSMESSAGE_FILES_PERFORMATIVE
_IPFSMESSAGE.fields_by_name[
    "get_files"
].message_type = _IPFSMESSAGE_GET_FILES_PERFORMATIVE
_IPFSMESSAGE.fields_by_name[
    "ipfs_hash"
].message_type = _IPFSMESSAGE_IPFS_HASH_PERFORMATIVE
_IPFSMESSAGE.fields_by_name[
    "store_files"
].message_type = _IPFSMESSAGE_STORE_FILES_PERFORMATIVE
_IPFSMESSAGE.oneofs_by_name["performative"].fields.append(
    _IPFSMESSAGE.fields_by_name["error"]
)
_IPFSMESSAGE.fields_by_name["error"].containing_oneof = _IPFSMESSAGE.oneofs_by_name[
    "performative"
]
_IPFSMESSAGE.oneofs_by_name["performative"].fields.append(
    _IPFSMESSAGE.fields_by_name["files"]
)
_IPFSMESSAGE.fields_by_name["files"].containing_oneof = _IPFSMESSAGE.oneofs_by_name[
    "performative"
]
_IPFSMESSAGE.oneofs_by_name["performative"].fields.append(
    _IPFSMESSAGE.fields_by_name["get_files"]
)
_IPFSMESSAGE.fields_by_name["get_files"].containing_oneof = _IPFSMESSAGE.oneofs_by_name[
    "performative"
]
_IPFSMESSAGE.oneofs_by_name["performative"].fields.append(
    _IPFSMESSAGE.fields_by_name["ipfs_hash"]
)
_IPFSMESSAGE.fields_by_name["ipfs_hash"].containing_oneof = _IPFSMESSAGE.oneofs_by_name[
    "performative"
]
_IPFSMESSAGE.oneofs_by_name["performative"].fields.append(
    _IPFSMESSAGE.fields_by_name["store_files"]
)
_IPFSMESSAGE.fields_by_name[
    "store_files"
].containing_oneof = _IPFSMESSAGE.oneofs_by_name["performative"]
DESCRIPTOR.message_types_by_name["IpfsMessage"] = _IPFSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IpfsMessage = _reflection.GeneratedProtocolMessageType(
    "IpfsMessage",
    (_message.Message,),
    dict(
        Store_Files_Performative=_reflection.GeneratedProtocolMessageType(
            "Store_Files_Performative",
            (_message.Message,),
            dict(
                FilesEntry=_reflection.GeneratedProtocolMessageType(
                    "FilesEntry",
                    (_message.Message,),
                    dict(
                        DESCRIPTOR=_IPFSMESSAGE_STORE_FILES_PERFORMATIVE_FILESENTRY,
                        __module__="ipfs_pb2"
                        # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative.FilesEntry)
                    ),
                ),
                DESCRIPTOR=_IPFSMESSAGE_STORE_FILES_PERFORMATIVE,
                __module__="ipfs_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Store_Files_Performative)
            ),
        ),
        Ipfs_Hash_Performative=_reflection.GeneratedProtocolMessageType(
            "Ipfs_Hash_Performative",
            (_message.Message,),
            dict(
                DESCRIPTOR=_IPFSMESSAGE_IPFS_HASH_PERFORMATIVE,
                __module__="ipfs_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Ipfs_Hash_Performative)
            ),
        ),
        Get_Files_Performative=_reflection.GeneratedProtocolMessageType(
            "Get_Files_Performative",
            (_message.Message,),
            dict(
                DESCRIPTOR=_IPFSMESSAGE_GET_FILES_PERFORMATIVE,
                __module__="ipfs_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Get_Files_Performative)
            ),
        ),
        Files_Performative=_reflection.GeneratedProtocolMessageType(
            "Files_Performative",
            (_message.Message,),
            dict(
                FilesEntry=_reflection.GeneratedProtocolMessageType(
                    "FilesEntry",
                    (_message.Message,),
                    dict(
                        DESCRIPTOR=_IPFSMESSAGE_FILES_PERFORMATIVE_FILESENTRY,
                        __module__="ipfs_pb2"
                        # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative.FilesEntry)
                    ),
                ),
                DESCRIPTOR=_IPFSMESSAGE_FILES_PERFORMATIVE,
                __module__="ipfs_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Files_Performative)
            ),
        ),
        Error_Performative=_reflection.GeneratedProtocolMessageType(
            "Error_Performative",
            (_message.Message,),
            dict(
                DESCRIPTOR=_IPFSMESSAGE_ERROR_PERFORMATIVE,
                __module__="ipfs_pb2"
                # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage.Error_Performative)
            ),
        ),
        DESCRIPTOR=_IPFSMESSAGE,
        __module__="ipfs_pb2"
        # @@protoc_insertion_point(class_scope:aea.valory.ipfs.v0_1_0.IpfsMessage)
    ),
)
_sym_db.RegisterMessage(IpfsMessage)
_sym_db.RegisterMessage(IpfsMessage.Store_Files_Performative)
_sym_db.RegisterMessage(IpfsMessage.Store_Files_Performative.FilesEntry)
_sym_db.RegisterMessage(IpfsMessage.Ipfs_Hash_Performative)
_sym_db.RegisterMessage(IpfsMessage.Get_Files_Performative)
_sym_db.RegisterMessage(IpfsMessage.Files_Performative)
_sym_db.RegisterMessage(IpfsMessage.Files_Performative.FilesEntry)
_sym_db.RegisterMessage(IpfsMessage.Error_Performative)


_IPFSMESSAGE_STORE_FILES_PERFORMATIVE_FILESENTRY._options = None
_IPFSMESSAGE_FILES_PERFORMATIVE_FILESENTRY._options = None
# @@protoc_insertion_point(module_scope)
